#ifndef CONFIG_H_
#define CONFIG_H_

#include "sdkconfig.h"

#define WIFI_SSID CONFIG_WIFI_SSID
#define WIFI_PASSWORD CONFIG_WIFI_PASSWORD

#define MQTT_URI CONFIG_MQTT_URI
#define MQTT_TOPIC_PREFIX CONFIG_MQTT_TOPIC_PREFIX
#define MQTT_TOPIC_VERSION CONFIG_MQTT_TOPIC_VERSION

#define DEVICE_ID CONFIG_DEVICE_ID
#define DEVICE_NAME CONFIG_DEVICE_NAME
#define ESP32_MODEL CONFIG_ESP32_MODEL
#define MANUFACTURER CONFIG_MANUFACTURER

#define NTP_SERVER CONFIG_NTP_SERVER
#define NTP_TZ CONFIG_NTP_TZ

#endif /* CONFIG_H_ */
