#ifndef ZONE_CONFIG_H_
#define ZONE_CONFIG_H_

#include "sdkconfig.h"

#define ZONE_ACTIVE_LEVEL 1
#define ZONE_COUNT 6

/* After this much idle time in MANUAL with no zone active, return to AUTO */
#define AUTO_MODE_RESET_TIME_MIN CONFIG_AUTO_MODE_RESET_TIME_MIN

#define DURATION_0_STR STR(CONFIG_DURATION_0)
#define DURATION_1_STR STR(CONFIG_DURATION_1)
#define DURATION_2_STR STR(CONFIG_DURATION_2)
#define DURATION_3_STR STR(CONFIG_DURATION_3)

#define GPIO_ZONE_1 CONFIG_GPIO_ZONE_1
#define GPIO_ZONE_2 CONFIG_GPIO_ZONE_2
#define GPIO_ZONE_3 CONFIG_GPIO_ZONE_3
#define GPIO_ZONE_4 CONFIG_GPIO_ZONE_4
#define GPIO_ZONE_5 CONFIG_GPIO_ZONE_5
#define GPIO_ZONE_6 CONFIG_GPIO_ZONE_6

#endif /* ZONE_CONFIG_H_ */
