#ifndef BUTTON_CONFIG_H_
#define BUTTON_CONFIG_H_

#include "sdkconfig.h"

#define BUTTON_ACTIVE_LEVEL 0

#define BUTTON_LONG_PRESS_TIME 1000
#define BUTTON_SHORT_PRESS_TIME 200

#define GPIO_BTN_ZONE_1 CONFIG_GPIO_BTN_ZONE_1
#define GPIO_BTN_ZONE_2 CONFIG_GPIO_BTN_ZONE_2
#define GPIO_BTN_ZONE_3 CONFIG_GPIO_BTN_ZONE_3
#define GPIO_BTN_ZONE_4 CONFIG_GPIO_BTN_ZONE_4
#define GPIO_BTN_ZONE_5 CONFIG_GPIO_BTN_ZONE_5
#define GPIO_BTN_ZONE_6 CONFIG_GPIO_BTN_ZONE_6

#endif /* BUTTON_CONFIG_H_ */
